### PR TITLE
MecanumDrive odometry and tf functions implementation

### PR DESCRIPTION
**Pull request by danilogsch**
Signed-off-by: danilo_gsch <danilo_gsch@hotmail.com>
Danilo Schneider

# 🎉 New feature

Closes [#683](https://github.com/gazebosim/gz-sim/pull/683) [#1619](https://github.com/gazebosim/gz-sim/issues/1619)

## Summary
Implementation of Mecanum drive odometry and tf based on the implementation of the Differential robot.

## Test it
Run mecanum_drive.sdf and listen for odometry and tf topics.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by danilogsch** [comment]
Depends on [#486](https://github.com/gazebosim/gz-math/pull/486)

**Comment by azeey** [comment]
Waiting on https://github.com/gazebosim/gz-math/pull/486

**Comment by mjcarroll** [comment]
@danilogsch if you can address feedback on the math pull request, I can begin reviewing this one.

**Comment by mjcarroll** [comment]
@danilogsch the math PR has been landed, can you add a test here to verify the behavior of the system?

**Comment by azeey** [comment]
I've removed the `beta` label. We can merge this after Harmonic is released.

**Comment by muttistefano** [comment]
Hi all, any information regarding when this PR will be included?
I see some failures in the automatic build, is this due to the PR or still the math dependency ? 
In case I can help.
Thanks

**Comment by azeey** [comment]
I didn't realize https://github.com/gazebosim/gz-sim/pull/2297 replaced this. Closing.

**Pull request closed without merging**
