### PR TITLE
Backport #1748: Adds a tool for environment data visualization and custom environmental sensors

### PR DESCRIPTION
**Pull request by arjo129**
🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

# 🎉 New feature

Closes #<NUMBER>

## Summary
This PR adds a tool to visualize Scalar Environmental Data. It also adds custom sensors. It is a backport of #1748 

Signed-off-by: Arjo Chakravarty <arjo@openrobotics.org>

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by hidmic — APPROVED** [review]
LGTM, just like #1748. Jenkins CI seems broken though.

**Comment by arjo129** [comment]
https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-ubuntu_auto-amd64/9909/ failing because of warnings triggered by code generated by Qt's moc. I don't think theres much I can do. Also I'm trying to understand the ABI checker.

**Comment by hidmic** [comment]
@arjo129 hmm, I think we can still solve those issues (or they will come back to hunt us in the future).

On Windows, it looks like we have visibility issues.
```
error LNK2001: unresolved external symbol "class std::optional<class gz::math::v7::Vector3<double> > __cdecl gz::sim::v7::getGridFieldCoordinates(class gz::sim::v7::EntityComponentManager const &,class gz::math::v7::Vector3<double> const &,class std::shared_ptr<struct gz::sim::v7::components::EnvironmentalData> const &)" (?getGridFieldCoordinates@v7@sim@gz@@YA?AV?$optional@V?$Vector3@N@v7@math@gz@@@std@@AEBVEntityComponentManager@123@AEBV?$Vector3@N@1math@3@AEBV?$shared_ptr@UEnvironmentalData@components@v7@sim@gz@@@5@@Z) [C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\gz-sim7\src\gui\plugins\environment_visualization\EnvironmentVisualization.vcxproj]
```

Namely, `getGridFieldCoordinates` is missing a `GZ_SIM_VISIBLE` attribute.

On Ubuntu, I suspect that it is the use of the `Q_PROPERTY(... MEMBER ...)` form that is triggering bad code generation within the MOC. It is the first instance of this form I see in the codebase.

And while the ABI checker output is pretty much useless, I suspect it takes issue with the changes to the `EnvironmentalData` struct, none of which are ABI compatible even if API compatible.

**Comment by arjo129** [comment]
Test failures are now unrelated. Going to merge.

**Pull request merged**
