### PR TITLE
Fix overflow if dropStr is large

### PR DESCRIPTION
**Pull request by onurtore**
# 🦟 Bug fix

Fixes  https://github.com/gazebosim/gz-common/pull/393

## Summary
Large mesh file names creates ugly error message due to overflow. This commit fixes this.
## Checklist
- [X] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by chapulina** [comment]
You may want to target this at the `gz-sim7` branch, so that the fix goes into the initial Garden release

**Comment by onurtore** [comment]
> You may want to target this at the `gz-sim7` branch, so that the fix goes into the initial Garden release

Do I have to create new PR for that?

**Comment by ahcorde** [comment]
> > You may want to target this at the `gz-sim7` branch, so that the fix goes into the initial Garden release
> 
> Do I have to create new PR for that?

I already did it, you should:

```shell
git fetch
git merge origin/gz-sim7
git push origin otore19/addNewLine2
```

**Review by ahcorde — CHANGES_REQUESTED** [review]
please resolve the conflicts

**Review by azeey — APPROVED** [review]
I've resolved the conflict and made a small change. I've also tested the code on [godbolt](https://godbolt.org/z/aKKGz3fGa) . LGTM!

**Comment by azeey** [comment]
Homebrew failures don't seem to be related to this PR. Merging.

**Pull request merged**
