### PR TITLE
  Enable HIDE_SYMBOLS_BY_DEFAULT + linux patches

### PR DESCRIPTION
**Pull request by j-rivero**
# 🎉 New feature

## Summary
Part of https://github.com/gazebosim/gz-cmake/pull/392 and https://github.com/gazebosim/gz-cmake/issues/166.

## Test it
The PR enables the HIDE_SYMBOLS_BY_DEFAULT option and patch the failures found during the build on Linux.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by mjcarroll** [comment]
Looks like there are some bad interactions with Qt on Windows:

```
C:\J\workspace\gz_sim-pr-win\ws\build\gz-sim9\src\gui\plugins\joint_position_controller\moc_JointPositionController.cpp(78,1): warning C4273: 'gz::sim::gui::JointsModel::qt_static_metacall': inconsistent dll linkage [C:\J\workspace\gz_sim-pr-win\ws\build\gz-sim9\src\gui\plugins\joint_position_controller\JointPositionController.vcxproj]

C:\J\workspace\gz_sim-pr-win\ws\build\gz-sim9\src\gui\plugins\joint_position_controller\../../../../../../gz-sim/src/gui/plugins/joint_position_controller/JointPositionController.hh(42,5): message : see previous definition of 'qt_static_metacall' (compiling source file C:\J\workspace\gz_sim-pr-win\ws\build\gz-sim9\src\gui\plugins\joint_position_controller\moc_JointPositionController.cpp) [C:\J\workspace\gz_sim-pr-win\ws\build\gz-sim9\src\gui\plugins\joint_position_controller\JointPositionController.vcxproj]

C:\J\workspace\gz_sim-pr-win\ws\build\gz-sim9\src\gui\plugins\joint_position_controller\moc_JointPositionController.cpp(92,84): warning C4273: 'staticMetaObject': inconsistent dll linkage [C:\J\workspace\gz_sim-pr-win\ws\build\gz-sim9\src\gui\plugins\joint_position_controller\JointPositionController.vcxproj]

C:\J\workspace\gz_sim-pr-win\ws\build\gz-sim9\src\gui\plugins\joint_position_controller\../../../../../../gz-sim/src/gui/plugins/joint_position_controller/JointPositionController.hh(42,5): message : see previous definition of 'public: static QMetaObject const gz::sim::gui::JointsModel::staticMetaObject' (compiling source file C:\J\workspace\gz_sim-pr-win\ws\build\gz-sim9\src\gui\plugins\joint_position_controller\moc_JointPositionController.cpp) [C:\J\workspace\gz_sim-pr-win\ws\build\gz-sim9\src\gui\plugins\joint_position_controller\JointPositionController.vcxproj]

C:\J\workspace\gz_sim-pr-win\ws\build\gz-sim9\src\gui\plugins\joint_position_controller\moc_JointPositionController.cpp(92,84): error C2491: 'gz::sim::gui::JointsModel::staticMetaObject': definition of dllimport static data member not allowed [C:\J\workspace\gz_sim-pr-win\ws\build\gz-sim9\src\gui\plugins\joint_position_controller\JointPositionController.vcxproj]
```

Linux appears to be fine, though (just a known-flaky test)

**Comment by j-rivero** [comment]
Builds are fine in the three platforms but there are some warnings on Windows and test failures on Linux and Mac that does not sound to me like related to these changes.

**Comment by azeey** [comment]
> Builds are fine in the three platforms but there are some warnings on Windows and test failures on Linux and Mac that does not sound to me like related to these changes.

Yup, I think the test failures on Linux and Mac are known issues. I believe the warnings on windows were fixed on gz-sim8.

**Review by azeey — APPROVED** [review]
LGTM! But do you know why some plugins need to export symbols while others don't?

**Comment by j-rivero** [comment]
> LGTM! But do you know why some plugins need to export symbols while others don't?

That is a good question now that I'm looking at it slowly without the patching hammer on. Windows problems seems to appear on plugins when I added the `GZ_SIM_GUI_VISIBLE` keyword to them. The problems appeared on the moc_ generation so I assumed that it has something to do with that qt moc generation but I did not find any particular reason why this happens on the plot3D plugin for example.

I've removed the visibility key from both in a custom branch: [Build Status](https://build.osrfoundation.org/job/gz_sim-pr-win/64/) let's see what happen.

**Comment by j-rivero** [comment]
> I've removed the visibility key from both in a custom branch: [![Build Status](https://camo.githubusercontent.com/2c643c61b4055cbc226d722daa6dd900d233805d5c05bf0698923294c34c1ff2/68747470733a2f2f6275696c642e6f7372666f756e646174696f6e2e6f72672f6275696c645374617475732f69636f6e3f6a6f623d677a5f73696d2d70722d77696e266275696c643d3634)](https://build.osrfoundation.org/job/gz_sim-pr-win/64/) let's see what happen.

Windows did not have problems on building without plugin keywords. However I tried the same on Linux and that failed with missing symbols while compiling the gui **TEST** files:

```
 src/gui/plugins ❯ find . -name *_TEST*                                                                                                                                                                                                                                                                           
  ./plot_3d/Plot3D_TEST.cc                                                                                                                                                                                                                                                                                                                                                                    
  ./joint_position_controller/JointPositionController_TEST.cc 
```

The PR patches the two plugins because we are only implementing `_TEST` on both so we only need binary symbols on these two. By now.

**Pull request merged**
