### PR TITLE
Add QML Debugging support

### PR DESCRIPTION
**Pull request by darksylinc**
The project must be rebuilt defining the QT_QML_DEBUG macro.

Once that's done, loading the GUI will wait until the debugger is
attached to port 40000.

QtCreator does this automatically when setting:
  Projects -> Build -> QML debugging and profiling -> Enable

Tested with QtCreator (Qt Quick plugin enabled) and working.

Signed-off-by: Matias N. Goldberg <dark_sylinc@yahoo.com.ar>

# 🦟 Bug fix

No ticket was created for this issue.

## Summary

Troubleshooting QML errors in Javascript code is a PITA without proper tools.
This PR addresses that.

Usually QML debugging is handled automatically by appending the right command line entry.

However IGN is special because it's a so loaded by a ruby script; hence all command line arguments added by QtCreator are lost (and may also result in failure to start).

A quick solution is to hardcode those commands when compiling with `QT_QML_DEBUG`.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by mayman99** [comment]
Thanks for the PR!
I've a question, would it possible to expose the debug option thru the starting ruby script?

**Review by mayman99 — CHANGES_REQUESTED** [review]
I think exposing this feature thru a tutorial or an example would be a better idea for usability, because if merged like this the only way users would know about the feature is by reading the source code.

**Comment by darksylinc** [comment]
OK I added gazebosim/docs#251 as documentation that should accompany this new feature.

Is it satisfactory?

**Review by mayman99 — APPROVED** [review]
lgtm!
thanks for the PR!

**Pull request merged**
