### PR TITLE
Enable 24.04 CI, require cmake 3.22.1

### PR DESCRIPTION
**Pull request by scpeters**
# 🎉 New feature

Part of https://github.com/gazebosim/gz-cmake/issues/350.

## Summary

This adds a GitHub workflow using Noble and increases our minimum required cmake version to 3.22.1 since we are already requiring that in gz-cmake4. It also removes some old code to support older versions of cmake.

## Test it

Look at the 24.04 CI results.

## Checklist
- [X] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [X] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by scpeters** [comment]
there are some cmake warnings that should be resolved

**Comment by scpeters** [comment]
> there are some cmake warnings that should be resolved

actually these cmake warnings are preexisting on `main`, but I'll see if I can fix them here anyway

* [Build Status](https://build.osrfoundation.org/view/gz-ionic/job/gz_sim-ci-main-noble-amd64/3/) https://build.osrfoundation.org/view/gz-ionic/job/gz_sim-ci-main-noble-amd64/3/cmake/

**Comment by scpeters** [comment]
> > there are some cmake warnings that should be resolved
> 
> actually these cmake warnings are preexisting on `main`, but I'll see if I can fix them here anyway
> 
> * [Build Status](https://build.osrfoundation.org/view/gz-ionic/job/gz_sim-ci-main-noble-amd64/3/) https://build.osrfoundation.org/view/gz-ionic/job/gz_sim-ci-main-noble-amd64/3/cmake/

fix from https://github.com/gazebosim/gz-sim/pull/2397 is being merged forward in https://github.com/gazebosim/gz-sim/pull/2422

**Comment by scpeters** [comment]
CI is relatively happy now, just a flaky test failure on windows

* test failure: https://build.osrfoundation.org/job/gz_sim-pr-win/453/testReport/junit/(root)/INTEGRATION_mesh_inertia_calculation/test_ran/history/
* passing history on `main`: https://build.osrfoundation.org/job/gz_sim-main-win/54/testReport/(root)/MeshInertiaCalculationTest/history/
* failing history on `main`: https://build.osrfoundation.org/job/gz_sim-main-win/53/testReport/junit/(root)/INTEGRATION_mesh_inertia_calculation/test_ran/history/

**Review by iche033 — APPROVED** [review]

**Pull request merged**
