### PR TITLE
Merge 8 -> main

### PR DESCRIPTION
**Pull request by iche033**
# ➡️ Forward port

Port gz-sim8 to main

Branch comparison: https://github.com/gazebosim/gz-sim/compare/main...gz-sim8

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Review by jennuine — APPROVED** [review]

**Review by azeey — APPROVED** [review]

**Comment by iche033** [comment]
I've seen `UNIT_Server_TEST` test failed before but it looks like it is now failing consistently on all CI builds. The test passes locally. Checking if it's introduced by this forward port PR or if there are timing changes that made it more easy to fail now.

**Comment by iche033** [comment]
there are also new compile warnings in main. I created a separate PR to fix them: https://github.com/gazebosim/gz-sim/pull/2535

**Comment by azeey** [comment]
Rerunning the Noble Github Actions job. I think the failures was flaky.

**Comment by iche033** [comment]
looks like the `INTEGRATION_log_system` test is failing consistently on ubuntu noble github actions

**Comment by iche033** [comment]
> looks like the `INTEGRATION_log_system` test is failing consistently on ubuntu noble github actions

testing to see if https://github.com/gazebosim/gz-sim/pull/2539 fixes the test

**Comment by iche033** [comment]
`INTEGRATION_log_system` test is fixed. I think the windows `INTEGRATION_save_world` is flaky. I've seen it fail before. 

Merging.

**Pull request merged**
