### PR TITLE
Cherry-Pick #1836: Use a queue to track component registration from multiple sources

### PR DESCRIPTION
**Pull request by azeey**
# 🦟 Bug fix

Cherry-Pick #1836 with `ign->gz` changes.

## Summary

When a plugin gets unloaded, the component types it registered will have invalid component descriptors. Attempting to create new components of those types will result in a segfault. This PR is an attempt to fix that by keeping track of all component registrations and removing invalid ones when plugins get unloaded.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Rebase-and-merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by mjcarroll — APPROVED** [review]
LGTM with green CI

**Comment by scpeters** [comment]
`INTEGRATION_recreate_entities` is failing by seg-fault on all Ubuntu CI jobs (Jenkins and both GitHub workflows)

**Comment by scpeters** [comment]
> `INTEGRATION_recreate_entities` is failing by seg-fault on all Ubuntu CI jobs (Jenkins and both GitHub workflows)

actually this test is already failing on `gz-sim7`

* https://build.osrfoundation.org/view/ign-garden/job/ignition_gazebo-ci-gz-sim7-focal-amd64/85/testReport/(root)/INTEGRATION_recreate_entities/test_ran/

issue posted here: https://github.com/gazebosim/gz-sim/issues/1946

**Comment by azeey** [comment]
@osrf-jenkins run tests please

**Comment by azeey** [comment]
CI is green except for known failures. Merging!

**Pull request merged**
