### PR TITLE
Make systems and tests include headers they use

### PR DESCRIPTION
**Pull request by mjcarroll**
Split from #2087

### CODE REVIEW

**Review by nkoenig — APPROVED** [review]

**Comment by nkoenig** [comment]
Jenkins can't find a few packages (libgz-physics7, libsdformat14, and python3-sdformat14), and the user_commands test is failing which I assume is because a new prerelease of gz-msgs has not been made.

**Comment by iche033** [comment]
The pre-releases were made but not being picked up. I think https://github.com/gazebo-tooling/gzdev/pull/69 may fix this issue.

**Comment by iche033** [comment]
@osrf-jenkins run tests please

**Comment by azeey** [comment]
> @osrf-jenkins run tests please

oops, I was running just the Jammy build manually.

**Comment by iche033** [comment]
> oops, I was running just the Jammy build manually. 

ouch sorry!

**Comment by azeey** [comment]
Tests are passing on Linux and macOS on Jenkins. Merging!

**Pull request merged**
