### PR TITLE
Fix Protobuf Windows warnings on ign-gazebo6

### PR DESCRIPTION
**Pull request by Blast545**
Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>

## Summary
First step towards #1256
## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by chapulina** [comment]
Just checking if this PR is meant to target `ign-gazebo6` or `ign-gazebo5`. The title and base branches are conflicting.

**Comment by Blast545** [comment]
Wrapping the headers does not address any of the current warnings: https://build.osrfoundation.org/job/ign_gazebo-pr-win/3671/msbuild/ . 

After checking with more detail the log output, I've seen that the output:

```
  Building Custom Rule C:/Jenkins/workspace/ign_gazebo-pr-win/ws/ign-gazebo/src/gui/plugins/scene3d/CMakeLists.txt

  Scene3D.cc

  moc_Scene3D.cpp

  qrc_GzScene3D.cpp

C:\vcpkg\installed\x64-windows\include\google/protobuf/stubs/logging.h(102,23): warning C4251: 'google::protobuf::internal::LogMessage::message_': class 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' needs to have dll-interface to be used by clients of class 'google::protobuf::internal::LogMessage' (compiling source file C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\ignition-gazebo5\src\gui\plugins\scene3d\moc_Scene3D.cpp) [C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\ignition-gazebo5\src\gui\plugins\scene3d\GzScene3D.vcxproj]
```
The first warnings come from adding a gz plugin, but those seem to be addressed with:

**Review by chapulina — APPROVED** [review]
Let's get this in since it's a step in the right direction. We can open follow-up PRs for the remaining warnings.

I've rebased this PR onto `ign-gazebo6`, because `ign-gazebo5` is EOL.

I also moved the compile flags from the headers to the mocced CC files in 2890efc38d60d77c071163965d54747ae84f7a4d to see if it helps.

**Comment by Blast545** [comment]
The PR job has the same amount of warnings, so this PR is not working as expected: https://build.osrfoundation.org/job/ign_gazebo-ign-6-win/106/

I stopped pushing in this direction because I wasn't able to figure out why the warnings are still being generated even with the pragmas and compiler flags. 

I will keep checking the remaining issues on Fortress, and if https://github.com/gazebosim/gz-msgs/pull/256 doesn't move forward I'll check the warnings issue more closely.

**Comment by chapulina** [comment]
Down from [585](https://build.osrfoundation.org/job/ign_gazebo-ign-6-win/106/) warnings to [403](https://build.osrfoundation.org/job/ign_gazebo-pr-win/4581/) 🚀

**Comment by chapulina** [comment]
Down to [375](https://build.osrfoundation.org/job/ign_gazebo-pr-win/4585/) 😄 Let's get this PR in since it's been open for a while, and follow-up PRs can be added as needed.

**Pull request merged**
