### PR TITLE
Fix Windows and Doxygen

### PR DESCRIPTION
**Pull request by chapulina**
# 🦟 Bug fix

* Closes https://github.com/gazebosim/gz-sim/issues/1409

### Windows

The Windows build has been broken since 

* #1536 

This fixes in adding `IGNITION_GAZEBO_GUI_VISIBLE`. The `GZ_SIM` equivalent has already been added to `gz-sim7` in #1633.

### Doxygen

After a lot of digging, it turned out that the Doxygen crashes described in #1409 were caused by the inline namespace. The Doxygen version on Jammy (1.9.1) can't handle those well.

### Warnings

Also fixed some compiler warnings that I saw on Jammy.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

### CODE REVIEW

**Comment by Blast545** [comment]
`jammy` builds are failing on `UNIT_Gui_TEST` and I haven't seen this one before, could it be related to the changes made on: src/gui/QuickStartHandler.hh?

**Comment by Blast545** [comment]
@ros-pull-request-builder retest this please

**Review by Blast545 — APPROVED** [review]

**Comment by Blast545** [comment]
I wanted to take a closer look to the errors on Jammy and `UNIT_Gui_TEST` before approving, I'll track this internally with @Crola1702

**Comment by chapulina** [comment]
> I wanted to take a closer look to the errors on Jammy and UNIT_Gui_TEST before approving, I'll track this internally with @Crola1702

Thanks! I believe those are pre-existing. It's good to get this PR in quickly so Windows CI runs and it doesn't get more broken.

**Pull request merged**
