### PR TITLE
Add optional binary relocatability

### PR DESCRIPTION
**Pull request by traversaro**
# 🎉 New feature

Closes part of https://github.com/gazebosim/gz-sim/issues/626

## Summary

This PR uses the changes introduced in gz-cmake3 in https://github.com/gazebosim/gz-cmake/pull/334 to support the cmake installation directory to be moved after the `make install` prefix, and continue to work without the need to set any special environment variable, as long as the library is compiled as shared. To avoid regressions and problems in Ubuntu Focal due to the use of std::filesystem, this new behaviour is only activated if the `GZ_ENABLE_RELOCATABLE_INSTALL` option is enabled, and its default value is `OFF` .

In particular, this PR defines the:
* `gz::sim::getGUIConfigPath()`
* `gz::sim::getSystemConfigPath()`
* `gz::sim::getServerConfigPath()`
* `gz::sim::getPluginInstallDir()`
* `gz::sim::getGUIPluginInstallDir()`
* `gz::sim::getWorldInstallDir()`

functions that should be used in place of:
* `GZ_SIM_GUI_CONFIG_PATH`
* `GZ_SIM_SYSTEM_CONFIG_PATH`
* `GZ_SIM_SERVER_CONFIG_PATH`
* `GZ_SIM_PLUGIN_INSTALL_DIR`
* `GZ_SIM_GUI_PLUGIN_INSTALL_DIR`
* `GZ_SIM_WORLD_INSTALL_DIR`  

macros to ensure that the library is relocatable.

Furthermore, this PR also deprecates the aforementioned macros, using the strategy described in https://stackoverflow.com/a/29297970 . That strategy works fine on GCC and Clang, while on MSVC it raise a warning:
~~~
warning C4068: unknown pragma
~~~

However, I think that it does anyhow the job of raising some kind of warning, and then at soon as the developer checks the macro definition the kind of warning is clear.

## Test it

The test should work as usual. The used CMake machinery is tested in https://github.com/gazebosim/gz-cmake/pull/334 .

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [x] Updated documentation (as needed)
- [x] Updated migration guide (as needed)
- [x] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by traversaro** [comment]
There is a failure:
~~~
2023-05-08T13:11:01.4765290Z  49/253 Test  #49: UNIT_Util_TEST .........................................***Failed    0.56 sec
2023-05-08T13:11:01.4766196Z Running main() from /github/workspace/test/gtest_vendor/src/gtest_main.cc
2023-05-08T13:11:01.4766690Z [==========] Running 12 tests from 1 test suite.
2023-05-08T13:11:01.4813371Z [----------] Global test environment set-up.
2023-05-08T13:11:01.4813697Z [----------] 12 tests from UtilTest
2023-05-08T13:11:01.4813967Z [ RUN      ] UtilTest.ScopedName
2023-05-08T13:11:01.4814241Z [       OK ] UtilTest.ScopedName (0 ms)
2023-05-08T13:11:01.4814550Z [ RUN      ] UtilTest.EntitiesFromScopedName
2023-05-08T13:11:01.4814876Z [       OK ] UtilTest.EntitiesFromScopedName (0 ms)
2023-05-08T13:11:01.4815159Z [ RUN      ] UtilTest.EntityTypeId
2023-05-08T13:11:01.4815436Z [       OK ] UtilTest.EntityTypeId (0 ms)
2023-05-08T13:11:01.4815711Z [ RUN      ] UtilTest.EntityTypeStr
2023-05-08T13:11:01.4815997Z [       OK ] UtilTest.EntityTypeStr (0 ms)
2023-05-08T13:11:01.4816301Z [ RUN      ] UtilTest.RemoveParentScopedName
2023-05-08T13:11:01.4816616Z [       OK ] UtilTest.RemoveParentScopedName (0 ms)
2023-05-08T13:11:01.4816905Z [ RUN      ] UtilTest.AsFullPath
2023-05-08T13:11:01.4817467Z [1;33m[Wrn] [Util.cc:399] [0m[1;33mCan't resolve full path for relative path [[0m[1;33mmeshes/collision.dae[0m[1;33m]. Loaded from a data-string.[0m[1;33m[0m
2023-05-08T13:11:01.4818123Z [1;33m[Wrn] [Util.cc:399] [0m[1;33mCan't resolve full path for relative path [[0m[1;33mmeshes\collision.dae[0m[1;33m]. Loaded from a data-string.[0m[1;33m[0m
2023-05-08T13:11:01.4818785Z [1;33m[Wrn] [Util.cc:399] [0m[1;33mCan't resolve full path for relative path [[0m[1;33mC:\path\to\collision.dae[0m[1;33m]. Loaded from a data-string.[0m[1;33m[0m
2023-05-08T13:11:01.4819171Z [       OK ] UtilTest.AsFullPath (0 ms)
2023-05-08T13:11:01.4819441Z [ RUN      ] UtilTest.TopLevelModel
2023-05-08T13:11:01.4819712Z [       OK ] UtilTest.TopLevelModel (0 ms)
2023-05-08T13:11:01.4819981Z [ RUN      ] UtilTest.ValidTopic
2023-05-08T13:11:01.4820402Z [1;31m[Err] [Util.cc:602] [0m[1;31mTopic [[0m[1;31m@~@~@~[0m[1;31m] is invalid, ignoring.[0m[1;31m[0m
2023-05-08T13:11:01.4820872Z [1;31m[Err] [Util.cc:602] [0m[1;31mTopic [[0m[1;31m@~@~@~[0m[1;31m] is invalid, ignoring.[0m[1;31m[0m
2023-05-08T13:11:01.4821317Z [1;31m[Err] [Util.cc:602] [0m[1;31mTopic [[0m[1;31m@~@~@~[0m[1;31m] is invalid, ignoring.[0m[1;31m[0m
2023-05-08T13:11:01.4821764Z [1;31m[Err] [Util.cc:602] [0m[1;31mTopic [[0m[1;31m@~@~@~[0m[1;31m] is invalid, ignoring.[0m[1;31m[0m
2023-05-08T13:11:01.4822284Z [1;36m[Dbg] [Util.cc:607] [0m[1;36mTopic [[0m[1;36mnot bad~[0m[1;36m] changed to valid topic [[0m[1;36mnot_bad[0m[1;36m][0m[1;36m[0m
2023-05-08T13:11:01.4822812Z [1;36m[Dbg] [Util.cc:607] [0m[1;36mTopic [[0m[1;36mnot bad~[0m[1;36m] changed to valid topic [[0m[1;36mnot_bad[0m[1;36m][0m[1;36m[0m
2023-05-08T13:11:01.4823358Z [1;36m[Dbg] [Util.cc:607] [0m[1;36mTopic [[0m[1;36mnot bad~[0m[1;36m] changed to valid topic [[0m[1;36mnot_bad[0m[1;36m][0m[1;36m[0m
2023-05-08T13:11:01.4823894Z [1;36m[Dbg] [Util.cc:607] [0m[1;36mTopic [[0m[1;36mnot bad~[0m[1;36m] changed to valid topic [[0m[1;36mnot_bad[0m[1;36m][0m[1;36m[0m
2023-05-08T13:11:01.4824428Z [1;36m[Dbg] [Util.cc:607] [0m[1;36mTopic [[0m[1;36mnot bad~[0m[1;36m] changed to valid topic [[0m[1;36mnot_bad[0m[1;36m][0m[1;36m[0m
2023-05-08T13:11:01.4824752Z [       OK ] UtilTest.ValidTopic (0 ms)
2023-05-08T13:11:01.4825041Z [ RUN      ] UtilTest.TopicFromScopedName
2023-05-08T13:11:01.4825356Z [       OK ] UtilTest.TopicFromScopedName (0 ms)
2023-05-08T13:11:01.4825639Z [ RUN      ] UtilTest.EnableComponent
2023-05-08T13:11:01.4825929Z [       OK ] UtilTest.EnableComponent (0 ms)
2023-05-08T13:11:01.4826207Z [ RUN      ] UtilTest.EntityFromMsg
2023-05-08T13:11:01.4826481Z [       OK ] UtilTest.EntityFromMsg (0 ms)
2023-05-08T13:11:01.4836759Z [ RUN      ] UtilTest.ResolveSdfWorldFile
2023-05-08T13:11:01.4837446Z [1;33m[Wrn] [LocalCache.cc:165] [0m[1;33mServer directory does not exist [[0m[1;33m/github/workspace/build/test/fake_home/.gz/fuel/fuel.gazebosim.org[0m[1;33m][0m
2023-05-08T13:11:01.4838313Z [1;33m[Wrn] [LocalCache.cc:165] [0m[1;33mServer directory does not exist [[0m[1;33m/github/workspace/build/test/fake_home/.gz/fuel/fuel.ignitionrobotics.org[0m[1;33m][0m
2023-05-08T13:11:01.4839205Z [1;33m[Wrn] [FuelClient.cc:1938] [0m[1;33mThe [0m[1;33mfuel.ignitionrobotics.org[0m[1;33m URL is deprecrated. Pleasse change [0m[1;33mhttps://fuel.ignitionrobotics.org[0m[1;33m to [0m[1;33mhttps://fuel.gazebosim.org[0m[1;33m[0m
2023-05-08T13:11:01.4839873Z [1;31m[Err] [SystemPaths.cc:525] [0m[1;31mCould not resolve file [[0m[1;31mshapes.sdf[0m[1;31m][0m[1;31m[0m
2023-05-08T13:11:01.4840641Z [1;32m[Msg] [0m[1;32mDownloading world [[0m[1;32mfuel.ignitionrobotics.org/openrobotics/worlds/test world[0m[1;32m][0m[1;32m[0m
2023-05-08T13:11:01.4841349Z [1;36m[Dbg] [Zip.cc:180] [0m[1;36mCreated file [[0m[1;36m/github/workspace/build/test/fake_home/.gz/fuel/fuel.ignitionrobotics.org/openrobotics/worlds/test world/2/test.sdf[0m[1;36m][0m[1;36m[0m
2023-05-08T13:11:01.4842125Z [1;36m[Dbg] [Zip.cc:180] [0m[1;36mCreated file [[0m[1;36m/github/workspace/build/test/fake_home/.gz/fuel/fuel.ignitionrobotics.org/openrobotics/worlds/test world/2/test.world[0m[1;36m][0m[1;36m[0m
2023-05-08T13:11:01.4842904Z [1;36m[Dbg] [Zip.cc:180] [0m[1;36mCreated file [[0m[1;36m/github/workspace/build/test/fake_home/.gz/fuel/fuel.ignitionrobotics.org/openrobotics/worlds/test world/2/thumbnails/1.png[0m[1;36m][0m[1;36m[0m
2023-05-08T13:11:01.4843409Z [1;32m[Msg] [0m[1;32mSaved world at:[0m[1;32m[0m
2023-05-08T13:11:01.4843923Z [1;32m  [0m[1;32m/github/workspace/build/test/fake_home/.gz/fuel/fuel.ignitionrobotics.org/openrobotics/worlds/test world/2[0m[1;32m[0m
2023-05-08T13:11:01.4844325Z /github/workspace/src/Util_TEST.cc:989: Failure
2023-05-08T13:11:01.4844643Z Value of: resolveSdfWorldFile("shapes.sdf").empty()
2023-05-08T13:11:01.4844898Z   Actual: true
2023-05-08T13:11:01.4845115Z Expected: false
2023-05-08T13:11:01.4845685Z [1;31m[Err] [SystemPaths.cc:534] [0m[1;31mFile [[0m[1;31m/invalid/does_not_exist.sdf[0m[1;31m] resolved to path [[0m[1;31m/invalid/does_not_exist.sdf[0m[1;31m] but the path does not exist[0m[1;31m[0m
2023-05-08T13:11:01.4846307Z [1;31m[Err] [SystemPaths.cc:525] [0m[1;31mCould not resolve file [[0m[1;31m../invalid/does_not_exist.sdf[0m[1;31m][0m[1;31m[0m
2023-05-08T13:11:01.4846690Z [  FAILED  ] UtilTest.ResolveSdfWorldFile (543 ms)
2023-05-08T13:11:01.4847066Z [----------] 12 tests from UtilTest (545 ms total)
~~~

**Comment by traversaro** [comment]
> Probably due to this line: https://github.com/gazebosim/gz-sim/blob/668b757c962e23f33c826487e4f725b3fd4486c5/src/Util.cc#LL823C30-L823C54 .

Fixed by https://github.com/gazebosim/gz-sim/pull/1968/commits/762a3823faaf301c1ae9ac5d13d388d686382124 .

**Comment by traversaro** [comment]
The Jenkins job failed as the test `INTEGRATION_reset_sensors` failed, not sure if it is related.

**Comment by traversaro** [comment]
> The Jenkins job failed as the test `INTEGRATION_reset_sensors` failed, not sure if it is related.

Apparently the failure disappeared now, so it was not related to the PR. All checks have passed.

**Review by mjcarroll — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks a lot @mjcarroll !

**Pull request merged**
