### PR TITLE
Add support for specifying log record period

### PR DESCRIPTION
**Pull request by iche033**
Signed-off-by: Ian Chen <ichen@osrfoundation.org>

# 🎉 New feature

## Summary

Current log recorder records states on every update. By specifying the log record period, the user is able to control how often the simulator records states.  A new command line arg `--record-period` is added (gazebo-classic also has the same arg name)

## Test it
Run the `INTEGRATION_log_system` test.

You can also try enabling log recording through the command line, e.g.

```sh
# record at 10ms instead of the default 1ms and save the log file in a `log_test` dir
ign gazebo -v 4 -r --record --record-path ./log_test --record-period 0.01  pendulum_links.sdf
```

then playback the log file:

```sh
ign gazebo -v 4 --playback  ./log_test
```

You should see that the playback is now choppy due to reduced recording rate.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by caguero — COMMENTED** [review]
Just for testing I tried `0.1` and `1` record-periods. I was expecting very choppy results but I think the playback stops for a lot of time. Not sure if there's something going on.

**Comment by iche033** [comment]
> Just for testing I tried `0.1` and `1` record-periods. I was expecting very choppy results but I think they playback stops for a lot of time. Not sure if there's something going on.

I can reproduce the issue. Just dumping my findings here: Found that it's to do with the `scene_broadcaster` in playback mode. It's not able to pick up [periodic changed states](https://github.com/gazebosim/gz-sim/blob/ign-gazebo6/src/systems/scene_broadcaster/SceneBroadcaster.cc#L377-L380) and send them to the gui. The logic has implicit assumption that states are updated often enough so that every time it's about to send the states to the gui, there are state changes available. However, log playback now updates at lower rate. You will only see the pendulum move if by some timing coincidence that log playback updates at the same iteration as when scenebroadcaster is about to publish its states.

I haven't found a good fix yet

**Comment by iche033** [comment]
playback scene broadcaster issue should be fixed in [f4728cc](https://github.com/gazebosim/gz-sim/pull/1636/commits/f4728ccccaeba0c39b9ee6fec56dbadaff99df9e). Now when no periodic changes are available when scene broadcaster is publishing,  I force it to do an offcycle state update the next time it sees periodic changes. This should ensure all changed states from log playback are published to the GUI.

**Review by caguero — APPROVED** [review]
Works for me now with `0.1` and `1`.

**Pull request merged**
