### PR TITLE
Backport cmdsim.rb: fix ruby syntax to ign-gazebo3

### PR DESCRIPTION
**Pull request by scpeters**
Backport #1884. Part of #1867.

This replaces File.exists? calls with File.exist? to fix the UNIT_gz_TEST on macOS. It also removes a
rescue statement that was hiding useful error messages.

**Note to maintainers**: Remember to use **Rebase-and-merge**.

### CODE REVIEW

**Comment by iche033** [comment]
hmm `CmdLine.CachedFuelWorld` is failing on ubuntu builds, not sure if it's related. Retriggered a couple of [github actions](https://github.com/gazebosim/gz-sim/actions/runs/4109042865)

**Comment by scpeters** [comment]
> hmm `CmdLine.CachedFuelWorld` is failing on ubuntu builds, not sure if it's related. Retriggered a couple of [github actions](https://github.com/gazebosim/gz-sim/actions/runs/4109042865)

maybe it will be fixed once https://github.com/gazebosim/gz-fuel-tools/pull/318 is released?

**Comment by scpeters** [comment]
> > hmm `CmdLine.CachedFuelWorld` is failing on ubuntu builds, not sure if it's related. Retriggered a couple of [github actions](https://github.com/gazebosim/gz-sim/actions/runs/4109042865)
> 
> maybe it will be fixed once [gazebosim/gz-fuel-tools#318](https://github.com/gazebosim/gz-fuel-tools/pull/318) is released?

I tested locally, and that appears to fix it. I've opened a PR to make a patch release of ign-fuel-tools 4.8.1 https://github.com/gazebosim/gz-fuel-tools/pull/325

**Comment by scpeters** [comment]
I just made the ign-fuel-tools 4.8.1 release and will restart CI

**Comment by scpeters** [comment]
the fuel tools 4.8.1 release didn't seem to fix the `CmdLine.CachedFuelWorld` test

**Comment by scpeters** [comment]
I believe the remaining CLI test is fixed by https://github.com/gazebosim/gz-sim/pull/1885/commits/34aadc89693dc9456dd7059e536336b7ec5dd685

**Review by iche033 — APPROVED** [review]

**Pull request merged**
