### PR TITLE
Add non concurrency to Ubuntu CI workflow

### PR DESCRIPTION
**Pull request by talregev**
Add non concurrency to Ubuntu CI workflow.

### CODE REVIEW

**Comment by mjcarroll** [comment]
Can you remove trailing whitespace from `.github/workflows/ci.yml` so we can pass pre-commit linting?

**Comment by talregev** [comment]
> Can you remove trailing whitespace from `.github/workflows/ci.yml` so we can pass pre-commit linting?

Yes.

**Comment by talregev** [comment]
@mjcarroll I removed trailing whitespace.
Please approve the CI that it will run the CI.

**Comment by talregev** [comment]
@mjcarroll 
Should I merge this to the gz-sim7 or the main? 
Not sure how the flow of the code is working here.

**Comment by mjcarroll** [comment]
> Should I merge this to the gz-sim7 or the main?

sim7 is fine, it will get picked up in a forward port.

**Review by azeey — APPROVED** [review]
Looks good to me based on https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value and https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow

**Pull request merged**
