### PR TITLE
Return absolute path when finding a resource

### PR DESCRIPTION
**Pull request by nkoenig**
Signed-off-by: Nate Koenig <nate@openrobotics.org>

# 🦟 Bug fix

## Summary

The `/gazebo/resource_paths/resolve` service would return a relative path to the gazebo server process. This is a problem when the requester is not executed at the same path as the gazebo server.

This fixes the issue by returning an absolute path.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by mjcarroll** [comment]
I believe I missed the original context for the resource service.  Is the intention that service will always be executed from the same machine as the running gazebo instance?

**Review by mabelzhang — APPROVED** [review]

**Comment by mabelzhang** [comment]
The compiler errors about `CubemapUri` - do these need a sdformat release?

**Comment by mjcarroll** [comment]
> The compiler errors about CubemapUri - do these need a sdformat release?

It needs this: https://github.com/gazebosim/gz-msgs/pull/306

**Comment by nkoenig** [comment]
It acutally need sdf12.6 release: https://github.com/gazebosim/sdformat/pull/1174

**Comment by nkoenig** [comment]
@mabelzhang feel free to approve the sdformat 12.6 release PR so that I can merge and kick off the release.

**Comment by mabelzhang** [comment]
Done!

**Pull request merged**
