### PR TITLE
Towards Green CI

### PR DESCRIPTION
**Pull request by mjcarroll**
# 🦟 Bug fix

## Summary

Fix things that are currently known-bad in CI.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by mjcarroll** [comment]
Getting much closer here!

On Windows we are down to 80 compiler warnings (in various places) and the "HydronamicsTest.VelcoityTestInOil" which has been failing for 70 builds now.

On Ubuntu we are down to [UNIT_Gui_clean_exit_TEST](https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-ubuntu_auto-amd64/9819/testReport/junit/(root)/UNIT_Gui_clean_exit_TEST/test_ran/) which segfaults...

**Comment by nkoenig** [comment]
I'm trying to reproduce the `UNIT_Gui_clean_exit_TEST` problem locally.

**Comment by mjcarroll** [comment]
I'm thinking that we disable and ticket this HydronamicsTest, I don't see any evidence that it ever worked.

**Comment by nkoenig** [comment]
I'm good with that plan

**Comment by mjcarroll** [comment]
> I'm good with that plan

I marked it as disabled on Windows.  We should be down to the GUI clean exit test and some Windows warnings.

**Comment by mjcarroll** [comment]
Remaining Windows warnings are coming from physics.  Addressed via: https://github.com/gazebosim/gz-physics/pull/446

**Comment by mjcarroll** [comment]
@osrf-jenkins retest this please

**Comment by nkoenig** [comment]
Window's warnings are gone. I'm unable to solve the server and gui tests easily, so I'll save those for another PR.

**Review by nkoenig — APPROVED** [review]

**Pull request merged**
