### PR TITLE
Merge 8 -> main

### PR DESCRIPTION
**Pull request by iche033**
# ➡️ Forward port

Port gz-sim8 to main

Branch comparison: https://github.com/gazebosim/gz-sim/compare/main...gz-sim8

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Comment by iche033** [comment]
depends on https://github.com/gazebosim/gz-msgs/pull/430

**Comment by iche033** [comment]
The `INTEGRATION_triggered_publisher` test is failing because it's receiving more msgs than expected. It's likely due to https://github.com/gazebosim/gz-transport/pull/479. If I revert to a gz-transport commit before the merge forward in [gz-transport](https://github.com/gazebosim/gz-transport/pull/479), the test passes. 

Interestingly if I run just that problematic test by itself, it passes:

```
./build/gz-sim9/bin/INTEGRATION_triggered_publisher --gtest_filter="*InputMessagesTriggerServices*"
```

I think it could be that the test is getting msgs from previous test that uses the same topic name, cc @caguero

**Comment by azeey** [comment]
I also noticed this and went down a rabbit hole. It turns out `gz::transport:NodeShared` in gz-transport is never destroyed. I thought when all the `gz::transport::Node` were destroyed, `NodeShared` would be destroyed as well, but this is not the case, so there is a good chance for tests to interfere with each other. I've worked on a potential solution: https://github.com/gazebosim/gz-transport/compare/gz-transport13...azeey:gz-transport:shared_ptr_for_nodeshared It fixes `INTEGRATION_triggered_publisher` for me.

**Comment by azeey** [comment]
`INTEGRATION_triggered_publisher` is also failing on [`gz-sim8`](https://build.osrfoundation.org/view/gz-harmonic/job/gz_sim-ci-gz-sim8-jammy-amd64/lastCompletedBuild/testReport/(root)/TriggeredPublisherTest/InputMessagesTriggerServices/) now (cc @claraberendsen). I'm fairly happy with https://github.com/gazebosim/gz-transport/pull/484, but we probably need a few eyes on it.

**Comment by iche033** [comment]
I think the gz-transport issue may take some time to fix. Can we get this in first?

**Review by caguero — APPROVED** [review]

**Review by bperseghetti — APPROVED** [review]

**Pull request merged**
