### PR TITLE
Merge ign-gazebo3 ➡️  ign-gazebo6

### PR DESCRIPTION
**Pull request by azeey**
# ➡️  Forward port

Port `ign-gazebo3 ` ➡️  `ign-gazebo6`

Branch comparison: https://github.com/gazebosim/gz-sim/compare/ign-gazebo6...ign-gazebo3

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Comment by azeey** [comment]
> Does this require an upstream release?
> 
> ```
>  [ 39%] Building CXX object src/gui/plugins/resource_spawner/CMakeFiles/ResourceSpawner.dir/ResourceSpawner.cc.o
>   /github/workspace/src/gui/plugins/resource_spawner/ResourceSpawner.cc: In lambda function:
>   /github/workspace/src/gui/plugins/resource_spawner/ResourceSpawner.cc:728:67: error: no matching function for call to 'ignition::fuel_tools::FuelClient::Models(ignition::fuel_tools::ModelIdentifier&, bool)'
>              for (auto iter = worker.fuelClient.Models(modelId, false);
>                                                                      ^
>   In file included from /github/workspace/src/gui/plugins/resource_spawner/ResourceSpawner.hh:27,
>                    from /github/workspace/src/gui/plugins/resource_spawner/ResourceSpawner.cc:18:
>   /usr/include/ignition/fuel_tools7/gz/fuel_tools/FuelClient.hh:113:25: note: candidate: 'ignition::fuel_tools::ModelIter ignition::fuel_tools::FuelClient::Models(const ignition::fuel_tools::ServerConfig&)'
>          public: ModelIter Models(const ServerConfig &_server);
>                            ^~~~~~
>   /usr/include/ignition/fuel_tools7/gz/fuel_tools/FuelClient.hh:113:25: note:   candidate expects 1 argument, 2 provided
>   /usr/include/ignition/fuel_tools7/gz/fuel_tools/FuelClient.hh:124:25: note: candidate: 'ignition::fuel_tools::ModelIter ignition::fuel_tools::FuelClient::Models(const ignition::fuel_tools::ServerConfig&) const'
>          public: ModelIter Models(const ServerConfig &_server) const;
>                            ^~~~~~
>   /usr/include/ignition/fuel_tools7/gz/fuel_tools/FuelClient.hh:124:25: note:   candidate expects 1 argument, 2 provided
>   /usr/include/ignition/fuel_tools7/gz/fuel_tools/FuelClient.hh:157:25: note: candidate: 'ignition::fuel_tools::ModelIter ignition::fuel_tools::FuelClient::Models(const ignition::fuel_tools::ModelIdentifier&)'
>          public: ModelIter Models(const ModelIdentifier &_id);
>                            ^~~~~~
>   /usr/include/ignition/fuel_tools7/gz/fuel_tools/FuelClient.hh:157:25: note:   candidate expects 1 argument, 2 provided
>   /usr/include/ignition/fuel_tools7/gz/fuel_tools/FuelClient.hh:166:25: note: candidate: 'ignition::fuel_tools::ModelIter ignition::fuel_tools::FuelClient::Models(const ignition::fuel_tools::ModelIdentifier&) const'
>          public: ModelIter Models(const ModelIdentifier &_id) const;
>                            ^~~~~~
>   /usr/include/ignition/fuel_tools7/gz/fuel_tools/FuelClient.hh:166:25: note:   candidate expects 1 argument, 2 provided
>   /usr/include/ignition/fuel_tools7/gz/fuel_tools/FuelClient.hh:172:25: note: candidate: 'ignition::fuel_tools::ModelIter ignition::fuel_tools::FuelClient::Models(const ignition::fuel_tools::CollectionIdentifier&) const'
>          public: ModelIter Models(const CollectionIdentifier &_id) const;
>                            ^~~~~~
>   /usr/include/ignition/fuel_tools7/gz/fuel_tools/FuelClient.hh:172:25: note:   candidate expects 1 argument, 2 provided
> ```

It does. I'll make one shortly.

**Comment by azeey** [comment]
@osrf-jenkins run tests please

**Comment by azeey** [comment]
> Is the windows failure part of the homebrew proto upgrade issue?

No, it's a test failure from a test that was added recently (in https://github.com/gazebosim/gz-sim/pull/1998). That PR targetted ign-gazebo3 which doesn't have windows CI.

**Comment by azeey** [comment]
I've updated the test in `Server_TEST.cc`
from 
```
  EXPECT_FALSE(*server.Running(0));
```
to 
```
  EXPECT_FALSE(server.Running(0).has_value());
```
because `server.Running(0)` will be returning a `nullopt` since there is no world at index 0 (the SDF doesn't contain one) and dereferencing a `nullopt` is undefined behavior.

I've also updated the branch to contain the latest PR added to ign-gazebo6.

**Review by nkoenig — APPROVED** [review]
This looks fine. I'll leave CI determination up to you.

**Comment by azeey** [comment]
The test failure on Ubuntu seems to also occur on the stable branch (https://build.osrfoundation.org/view/ign-fortress/job/ignition_gazebo-ci-ign-gazebo6-focal-amd64/178/) . The windows warnings are also (https://build.osrfoundation.org/view/ign-fortress/job/ign_gazebo-ign-6-win/177) even though they seem to disappear in newer builds. I think that's probably due to the workspace not being cleared (https://github.com/gazebo-tooling/release-tools/issues/724#issuecomment-1564561059). Merging!

**Pull request merged**
