### PR TITLE
Merge 6 -> 7

### PR DESCRIPTION
**Pull request by iche033**
# ➡️ Forward port

Port ign-gazebo6 to gz-sim7

Branch comparison: https://github.com/gazebosim/gz-sim/compare/gz-sim7...ign-gazebo6

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Comment by azeey** [comment]
Can we wait until https://github.com/gazebosim/gz-sim/pull/2398#discussion_r1643390612 is resolved to merge this?

**Comment by iche033** [comment]
yes this can wait

**Comment by azeey** [comment]
@Mergifyio update

**Comment by azeey** [comment]
> Can we wait until [#2398 (comment)](https://github.com/gazebosim/gz-sim/pull/2398#discussion_r1643390612) is resolved to merge this?
https://github.com/gazebosim/gz-sim/pull/2451 is merged, so we can move forward with this. Can you update the PR?

**Comment by iche033** [comment]
updated

**Review by azeey — APPROVED** [review]

**Pull request merged**
