### PR TITLE
Merge gz-sim8 ➡️  main

### PR DESCRIPTION
**Pull request by scpeters**
# ➡️  Forward port

Port `gz-sim8 ` ➡️  `main`

Branch comparison: https://github.com/gazebosim/gz-sim/compare/main...gz-sim8

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Comment by scpeters** [comment]
DCO is unhappy because of https://github.com/gazebosim/gz-sim/commit/d0c0322c84bd0c4ebcf6eaf8547bdda7883caced

**Comment by scpeters** [comment]
needs https://github.com/gazebosim/gz-fuel-tools/pull/429 to be merged forward

**Comment by scpeters** [comment]
> needs [gazebosim/gz-fuel-tools#429](https://github.com/gazebosim/gz-fuel-tools/pull/429) to be merged forward

https://github.com/gazebosim/gz-fuel-tools/pull/434

**Comment by scpeters** [comment]
> > needs [gazebosim/gz-fuel-tools#429](https://github.com/gazebosim/gz-fuel-tools/pull/429) to be merged forward
> 
> * [x]  [Merge gz-fuel-tools9 ➡️  main gz-fuel-tools#434](https://github.com/gazebosim/gz-fuel-tools/pull/434)

this is merged; manually restarting some CI jobs...

**Review by iche033 — APPROVED** [review]

**Comment by scpeters** [comment]
I'm going to manually ignore the DCO failiure in order to merge this

**Pull request merged**
