### PR TITLE
Use ignition::gazebo:: in class instantiation

### PR DESCRIPTION
**Pull request by scpeters**
# 🦟 Bug fix

Fixes macOS build.

## Summary

The macOS build has been broken since https://github.com/gazebosim/gz-sim/pull/1646:

* [Build Status](https://build.osrfoundation.org/view/ign-citadel/job/ignition_gazebo-ci-ign-gazebo3-homebrew-amd64/282/) https://build.osrfoundation.org/view/ign-citadel/job/ignition_gazebo-ci-ign-gazebo3-homebrew-amd64/282/

In other packages, I have avoided using the `gz::sim` namespace when implementing classes, so doing it here seems to fix the macOS build. The ABI build is broken too, but that needs a different fix.

## Checklist
- [X] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [X] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [X] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by mjcarroll** [comment]
macOS build doesn't seem to like that.

**Comment by scpeters** [comment]
> macOS build doesn't seem to like that.

it's because I removed broken bottles in https://github.com/osrf/homebrew-simulation/pull/2242, which maybe I didn't have to do as a separate step? At any rate, rebuilding the gz-common3 bottle in https://github.com/osrf/homebrew-simulation/pull/2245 which should fix it

**Comment by scpeters** [comment]
> > macOS build doesn't seem to like that.
> 
> it's because I removed broken bottles in [osrf/homebrew-simulation#2242](https://github.com/osrf/homebrew-simulation/pull/2242), which maybe I didn't have to do as a separate step? At any rate, rebuilding the gz-common3 bottle in [osrf/homebrew-simulation#2245](https://github.com/osrf/homebrew-simulation/pull/2245) which should fix it

homebrew build is now unstable, I believe because it ran on macos-monterey and there are some failing tests due to https://github.com/gazebosim/gz-physics/issues/442

**Comment by scpeters** [comment]
I believe the ABI checker is failing due to https://github.com/gazebosim/gz-sim/issues/1971

**Review by mjcarroll — APPROVED** [review]

**Comment by scpeters** [comment]
CI is 🟢 ! Hooray!

**Pull request merged**
