### PR TITLE
7 -> main 2022-12-07

### PR DESCRIPTION
**Pull request by iche033**
# ➡️ Forward port

Port gz-sim7 to main

Branch comparison: https://github.com/gazebosim/gz-sim/compare/main...gz-sim7

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Comment by mjcarroll** [comment]
If it's not critical, please hold on this one until https://github.com/gazebosim/gz-sim/pull/1783 is merged.

**Comment by iche033** [comment]
> If it's not critical, please hold on this one until #1783 is merged.

ok this can wait

**Comment by mjcarroll** [comment]
Okay @iche033 you are good to go here.

**Comment by iche033** [comment]
> Okay @iche033 you are good to go here.

merged from `main` and resolved conflicts [c77ffbf](https://github.com/gazebosim/gz-sim/pull/1835/commits/c77ffbf8b12d5fab7ad5b4bfdc6d339b2a6be33f)

**Pull request merged**
