### PR TITLE
Use same FP limits for TrackedVehicle to avoid self-moving

### PR DESCRIPTION
**Pull request by ntfshard**
# 🦟 Bug fix

Fixes https://github.com/gazebosim/gz-sim/issues/2506

## Summary
Using the same constants for checking against zero here to significantly reduce cases when system behaves in unexpected way.
Still for a solid solution we should consider a refactoring a whole algorithm.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by peci1** [comment]
LGTM.

I guess the constants could even be a bit higher unless you simulate mm-sized robots. The constants you suggest mean that any motion command above 0.000001 m/s or 0.000001 rad/s is considered non-straight motion. I guess no reasonably sized robot would react to a micrometer/sec command. On the other hand, I don't see anything really problematic practically with this constant.

**Review by peci1 — APPROVED** [review]

**Comment by peci1** [comment]
Could you please post the result of a test where you instruct the robot with e.g. 2e-6 linear and angular velocities?

**Comment by ntfshard** [comment]
I guess I can do it tomorrow, it's too late here, sorry. Maybe @iandresolares can provide, if he tested it

**Comment by ntfshard** [comment]
> Could you please post the result of a test where you instruct the robot with e.g. 2e-6 linear and angular velocities?

Yes, sure. It just standing still
[ubuntu22-screen0.webm](https://github.com/user-attachments/assets/3992e6f0-e526-4649-8d7a-6047c0f0f8ba)

**Comment by peci1** [comment]
Great, thanks! Now I'm more sure this PR will not have any bad side effects.

**Comment by azeey** [comment]
@osrf-jenkins run tests please

**Comment by ntfshard** [comment]
Can we have some conclusion about this hotfix? I mean it still affect us and we still need a backport to previous versions tbh

**Review by azeey — APPROVED** [review]

**Comment by azeey** [comment]
@ntfshard `gz-sim7` (Garden) has reached EOL and we won't be making anymore binary releases of it, so I'm going to backport this only to gz-sim8.

**Comment by azeey** [comment]
@mergifyio backport gz-sim8

**Pull request merged**
