### PR TITLE
Prepend to PYTHONPATH in tests

### PR DESCRIPTION
**Pull request by scpeters**
# 🦟 Bug fix

Fixes failing python tests

## Summary

Preserve the existing PYTHONPATH by prepending instead of replacing. This is needed since we started using a virtual environment in CI.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by scpeters** [comment]
I think both https://github.com/gazebosim/gz-sim/pull/2673/commits/e52797994b3ec4f2ab751213f43c9a3afa520688 and https://github.com/gazebo-tooling/release-tools/pull/1203 are needed to fix the python system loader integration test

**Comment by scpeters** [comment]
> I think both [e527979](https://github.com/gazebosim/gz-sim/commit/e52797994b3ec4f2ab751213f43c9a3afa520688) and [gazebo-tooling/release-tools#1203](https://github.com/gazebo-tooling/release-tools/pull/1203) are needed to fix the python system loader integration test

I'm going to temporarily reconfigure the homebrew jenkins job to use the release-tools branch from https://github.com/gazebo-tooling/release-tools/pull/1203

**Comment by scpeters** [comment]
@osrf-jenkins run tests please

**Review by azeey — APPROVED** [review]

**Comment by scpeters** [comment]
https://github.com/Mergifyio backport gz-sim8

**Pull request merged**
